# 🛠 Credit Risk Assessment System

# Data Preprocessing

---

## 📌 Project Overview

Data preprocessing is one of the most critical stages in the machine learning pipeline.

The objective of this notebook is to transform the raw dataset into a structured, machine learning-ready format by applying appropriate preprocessing techniques.

The processed dataset generated in this notebook will be used for training, evaluating, and deploying multiple machine learning models.

---

## 🎯 Objectives

In this notebook we will:

- Load the cleaned dataset
- Remove unnecessary features
- Separate input features and target variable
- Identify numerical and categorical columns
- Encode categorical variables
- Scale numerical features
- Perform Train-Test Split
- Save processed datasets
- Prepare reusable preprocessing functions for deployment

---

## 📈 Expected Outcome

By the end of this notebook, the dataset will be completely prepared for machine learning model development.

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

import os
import warnings

warnings.filterwarnings("ignore")

# Display Settings
pd.set_option("display.max_columns", None)

In [2]:
df = pd.read_csv("../data/raw/loan_default.csv")

df.head()

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0

# 📄 Create Dataset Copy

Creating a copy of the original dataset ensures that the raw data remains unchanged throughout the preprocessing pipeline.

In [3]:
data = df.copy()

data.head()

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0

# 🗑 Remove Unnecessary Columns

The `LoanID` column is a unique identifier and does not contribute to predicting loan default.

Therefore, it is removed before model development.

In [4]:
data.drop(columns=["LoanID"], inplace=True)

data.head()

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default
0,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0
1,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0
2,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1
3,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0
4,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0

# 🎯 Separate Features and Target

Machine learning models require the dataset to be separated into:

- Feature Matrix (X)
- Target Variable (y)

In [7]:
X = data.drop(columns=["Default"])   # Take all columns except the target
y = data["Default"]   # Target column

print("Feature Matrix Shape :", X.shape)
print("Target Shape :", y.shape)

Feature Matrix Shape : (255347, 16)
Target Shape : (255347,)

### Identify Numerical and Categorical Columns

In [8]:
numerical_features = X.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

categorical_features = X.select_dtypes(
    include=["object"]
).columns.tolist()

print("Numerical Features\n")
print(numerical_features)

print()

print("Categorical Features\n")
print(categorical_features)

Numerical Features

['Age', 'Income', 'LoanAmount', 'CreditScore', 'MonthsEmployed', 'NumCreditLines', 'InterestRate', 'LoanTerm', 'DTIRatio']

Categorical Features

['Education', 'EmploymentType', 'MaritalStatus', 'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner']

# 🔠 One-Hot Encoding

Machine learning algorithms require numerical input.

Categorical variables are transformed using **One-Hot Encoding**, which creates binary columns for each category while avoiding any artificial ordering between categories.

In [9]:
X = pd.get_dummies(
    X,
    columns=categorical_features,
    drop_first=True
)

X.head()

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education_High School,Education_Master's,Education_PhD,EmploymentType_Part-time,EmploymentType_Self-employed,EmploymentType_Unemployed,MaritalStatus_Married,MaritalStatus_Single,HasMortgage_Yes,HasDependents_Yes,LoanPurpose_Business,LoanPurpose_Education,LoanPurpose_Home,LoanPurpose_Other,HasCoSigner_Yes
0,56,85994,50587,520,80,4,15.23,36,0.44,False,False,False,False,False,False,False,False,True,True,False,False,False,True,True
1,69,50432,124440,458,15,1,4.81,60,0.68,False,True,False,False,False,False,True,False,False,False,False,False,False,True,True
2,46,84208,129188,451,26,3,21.17,24,0.31,False,True,False,False,False,True,False,False,True,True,False,False,False,False,False
3,32,31713,44799,743,0,3,7.07,24,0.23,True,False,False,False,False,False,True,False,False,False,True,False,False,False,False
4,60,20437,9139,633,8,4,6.51,48,0.73,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False

# 📏 Feature Scaling

Numerical features are standardized using **StandardScaler**.

Standardization improves the performance of algorithms such as Logistic Regression by ensuring all numerical features are on a comparable scale.

In [10]:
scaler = StandardScaler()

X[numerical_features] = scaler.fit_transform(
    X[numerical_features]
)

X.head()

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education_High School,Education_Master's,Education_PhD,EmploymentType_Part-time,EmploymentType_Self-employed,EmploymentType_Unemployed,MaritalStatus_Married,MaritalStatus_Single,HasMortgage_Yes,HasDependents_Yes,LoanPurpose_Business,LoanPurpose_Education,LoanPurpose_Home,LoanPurpose_Other,HasCoSigner_Yes
0,0.833990,0.089693,-1.086833,-0.341492,0.590533,1.341937,0.261771,-0.001526,-0.260753,False,False,False,False,False,False,False,False,True,True,False,False,False,True,True
1,1.701221,-0.823021,-0.044309,-0.731666,-1.285731,-1.343791,-1.308350,1.412793,0.778585,False,True,False,False,False,False,True,False,False,False,False,False,False,True,True
2,0.166888,0.043854,0.022715,-0.775718,-0.968209,0.446694,1.156831,-0.708685,-0.823728,False,True,False,False,False,True,False,False,True,True,False,False,False,False,False
3,-0.767053,-1.303452,-1.168538,1.061875,-1.718715,0.446694,-0.967805,-0.708685,-1.170174,True,False,False,False,False,False,True,False,False,False,True,False,False,False,False
4,1.100830,-1.592855,-1.671921,0.369631,-1.487790,1.341937,-1.052188,0.705634,0.995114,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training Features :", X_train.shape)

print("Testing Features :", X_test.shape)

print("Training Target :", y_train.shape)

print("Testing Target :", y_test.shape)

Training Features : (204277, 24)
Testing Features : (51070, 24)
Training Target : (204277,)
Testing Target : (51070,)

# 💾 Save Processed Dataset

The processed datasets are saved for reuse during model training and evaluation.

In [12]:
# Create processed data directory

os.makedirs("../data/processed", exist_ok=True)

# Save processed files

X_train.to_csv("../data/processed/X_train.csv", index=False)

X_test.to_csv("../data/processed/X_test.csv", index=False)

y_train.to_csv("../data/processed/y_train.csv", index=False)

y_test.to_csv("../data/processed/y_test.csv", index=False)

processed_data = pd.concat([X, y], axis=1)

processed_data.to_csv(
    "../data/processed/cleaned_data.csv",
    index=False
)

print("Processed dataset saved successfully.")

Processed dataset saved successfully.